import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

type CsvRow = Record<string, string>;

function parseArgs(argv: string[]) {
  let inFile = "";
  let outFile = "prisma/migrations/_media_urls_update.sql";
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--file") {
      inFile = (argv[i + 1] ?? "").trim();
      i += 1;
    } else if (arg === "--out") {
      outFile = (argv[i + 1] ?? "").trim();
      i += 1;
    }
  }
  if (!inFile) throw new Error("Missing required --file argument");
  return { inFile, outFile };
}

function parseCsv(input: string): CsvRow[] {
  const rows: string[][] = [];
  let currentField = "";
  let currentRow: string[] = [];
  let inQuotes = false;
  for (let i = 0; i < input.length; i += 1) {
    const ch = input[i];
    const next = input[i + 1];
    if (ch === "\"") {
      if (inQuotes && next === "\"") {
        currentField += "\"";
        i += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }
    if (ch === "," && !inQuotes) {
      currentRow.push(currentField);
      currentField = "";
      continue;
    }
    if ((ch === "\n" || ch === "\r") && !inQuotes) {
      if (ch === "\r" && next === "\n") i += 1;
      currentRow.push(currentField);
      currentField = "";
      if (currentRow.some((v) => v.length > 0)) rows.push(currentRow);
      currentRow = [];
      continue;
    }
    currentField += ch;
  }
  if (currentField.length > 0 || currentRow.length > 0) {
    currentRow.push(currentField);
    rows.push(currentRow);
  }
  if (!rows.length) return [];
  const headers = rows[0].map((h) => h.trim());
  return rows.slice(1).map((row) => {
    const out: CsvRow = {};
    for (let i = 0; i < headers.length; i += 1) out[headers[i]] = (row[i] ?? "").trim();
    return out;
  });
}

function sqlText(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

async function main() {
  const { inFile, outFile } = parseArgs(process.argv.slice(2));
  const raw = await readFile(path.resolve(process.cwd(), inFile), "utf8");
  const rows = parseCsv(raw);

  const sql: string[] = [];
  sql.push("-- Generated by scripts/generate-media-update-sql.ts");
  sql.push("-- Updates media URLs by slug");
  sql.push("BEGIN;");

  let updates = 0;
  for (const row of rows) {
    const slug = (row["slug"] ?? "").trim();
    if (!slug) continue;

    const playbackUrl = (row["playbackUrl"] ?? "").trim();
    const posterUrl = (row["posterUrl"] ?? "").trim();
    const heroPreviewUrl = (row["heroPreviewUrl"] ?? "").trim();

    const sets: string[] = [];
    if (playbackUrl) sets.push(`"playbackUrl"=${sqlText(playbackUrl)}`);
    if (posterUrl) sets.push(`"posterUrl"=${sqlText(posterUrl)}`);
    if (heroPreviewUrl) sets.push(`"heroPreviewUrl"=${sqlText(heroPreviewUrl)}`);
    if (!sets.length) continue;

    sets.push(`"videoStatus"='ready'`);
    sets.push(`"updatedAt"=now()`);

    sql.push(`UPDATE "ContentItem" SET ${sets.join(", ")} WHERE "slug"=${sqlText(slug)};`);
    updates += 1;
  }

  sql.push("COMMIT;");
  sql.push("");

  const outPath = path.resolve(process.cwd(), outFile);
  await writeFile(outPath, sql.join("\n"), "utf8");
  console.log(`Generated media update SQL at ${outPath} (${updates} UPDATE statements)`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});

